### ISSUE TITLE
Any plans to support offline mobile mode? 

### ISSUE THREAD

**Issue by khorozhansky** [XRM-OSS/Xrm-WebApi-Client#30]
Hi Florian,

Just in case, do you have any plans to cover a "seamless" supporting offline mode as well?  
Thanks

**Comment by DigitalFlow** [comment]
Hi @khorozhansky,

I do not have any actual plans, but this sounds like an interesting feature.
After taking a look at the offline query options I think that this might work well.

I'll take a look at it.
If you want to work on this as well in the meantime, feel free to open a PullRequest.

Thanks for your hint.

Kind Regards,
Florian

**Comment by DigitalFlow** [comment]
Probably easier to use Xrm.WebApi.offline by now for that scenario as it seems to be a seldom used feature.
Closing this for now, feel free to discuss if you have a different opinion on this.

Kind regards,
Florian
